version: "3"
services:
  db:
    build: ./database
    environment:
        SA_PASSWORD: "@Senha1234"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  webapi:
      build: ./src/TesteT2S.WebApi
      environment:
          ConnectionStrings__SqlServerConnection: "Server=db;Database=TesteT2S;User=sa;Password=@Senha1234;"
          CorsOptions__PolicyName: "AppCors"
          CorsOptions__AllowedOrigin: "http://localhost:4200"
      ports:
          - "5000:80"
      depends_on:
          - db
  webapp:
      build: ./src/TesteT2S.Frontend
      ports:
          - "4200:80"
