// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteT2S.WebApi.Data;

namespace TesteT2S.WebApi.Data.Migrations
{
    [DbContext(typeof(ContainerContext))]
    [Migration("20201122220537_addShipHandling")]
    partial class addShipHandling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TesteT2S.WebApi.Features.Containers.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Number");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("TesteT2S.WebApi.Features.ShipHandling.Models.Handling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<byte>("HandlingType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Ship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Handlings");
                });

            modelBuilder.Entity("TesteT2S.WebApi.Features.ShipHandling.Models.Handling", b =>
                {
                    b.HasOne("TesteT2S.WebApi.Features.Containers.Models.Container", "Container")
                        .WithMany("Handlings")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("TesteT2S.WebApi.Features.Containers.Models.Container", b =>
                {
                    b.Navigation("Handlings");
                });
#pragma warning restore 612, 618
        }
    }
}
