FROM node as build
WORKDIR /app
ENV PATH ./node_modules/.bin:$PATH
COPY package.json /app/
RUN npm install
COPY ./ /app/
ARG env=prod
RUN npm run build --prod

FROM nginx:1.13
COPY --from=build /app/nginx/nginx.conf /etc/nginx/
COPY --from=build /app/dist/teste-t2s-frontend /usr/share/nginx/html
